/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.sdist.vista;

import ec.edu.ups.sdist.controlador.Gestion;
import ec.edu.ups.sdist.controlador.ControladorChat;
import java.awt.Color;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author niel <Eduardo.Calle>
 */
public class PanelView extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel
     * @param controlador
     * @param controlChat
     */
    public PanelView(Gestion controlador, ControladorChat controlChat) {
        this.controlador = controlador;
        this.controlChat = controlChat;
        //initList();
        initComponents();
    }

    /* Establecemos nombre de nuestro usuario*/

    /**
     *
     * @param name
     */

    public void setUserName(String name) {
        userName.setText(name);
    }

    /* Establecemos estado de nuestro usuario*/

    /**
     *
     * @param stat
     */

    public void setStatus(String stat) {
        status.setText(stat);
    }

    /* Método para añadir un usuario a la lista de clientes*/

    /**
     *
     * @param name
     */

    public void addClientToList(String name) {
        panelUsers.addClientToList(name);
    }

    /* Método para añadir un grupo a la lista de grupos*/

    /**
     *
     * @param idGroup
     * @param name
     */

    public void agregarGrupoALista(String idGroup, String name) {
        panelGroups.addGroupToList(idGroup, name);
    }

    /* Método que elimina un cliente de la lista */

    /**
     *
     * @param name
     */

    public void removeClientToList(String name) {
        panelUsers.removeClientToList(name);
    }

    /* Método que elimina un grupo de la lista */

    /**
     *
     * @param name
     */

    public void removeGroupToList(String name) {
        panelGroups.removeGroupToList(name);
    }

    /* Al hacer doble click sobre un usuario este método abre la ventana de chat */

    /**
     *
     * @param selectedValue
     */

    public void openChat(String selectedValue) {
        controlChat.abrirChat(selectedValue);
    }

    /* Al hacer doble click sobre un grupo este método abre la venta de chat */

    /**
     *
     * @param idGroup
     * @param nameGroup
     */

    public void openGroupChat(String idGroup, String nameGroup) {
        controlChat.abrirConversacionGrupal(idGroup, nameGroup);
    }

    /* Este método llama al control del chat para que cree el nuevo grupo*/

    /**
     *
     * @param idGroup
     * @param nameGroup
     * @param users
     */

    public void createGroup(String idGroup, String nameGroup, ArrayList<String> users) {
        controlChat.crearGrupo(idGroup, nameGroup, users);
    }

    /**
     *
     * @param idGroup
     * @param nameGroup
     * @param users
     */
    public void addMoreUserToGroup(String idGroup, String nameGroup, ArrayList<String> users) {
        controlador.agregarInvUsuarioAGrupo(idGroup, nameGroup, users);
    }

    /* Este método llama al control del chat para indicar que abandonamos el grupo*/

    /**
     *
     * @param idGroup
     */

    public void leftGroup(String idGroup) {
        controlChat.abandonarChatGrupal(idGroup);
    }

    /**
     *
     * @param idGroString
     * @return
     */
    public HashMap getUserOfGroup(String idGroString) {
        return controlador.getGrupoObjetos(idGroString);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        photo = new javax.swing.JLabel(new ImageIcon(
            getClass().getResource("/componentes/images/Icon-user.png")));
    userName = new javax.swing.JLabel();
    status = new javax.swing.JLabel();
    tabbedPane = new javax.swing.JTabbedPane();
    createGroup = new javax.swing.JButton();
    addClient = new javax.swing.JButton();
    leaveGroup = new javax.swing.JButton();

    setBackground(java.awt.Color.darkGray);
    setLayout(new java.awt.GridBagLayout());
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridheight = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(1, 0, 0, 0);
    add(photo, gridBagConstraints);

    userName.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
    userName.setForeground(java.awt.Color.white);
    userName.setText("Usuario");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
    gridBagConstraints.insets = new java.awt.Insets(1, 0, 0, 1);
    add(userName, gridBagConstraints);

    status.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
    status.setForeground(java.awt.Color.green);
    status.setText("Conectado");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
    add(status, gridBagConstraints);

    panelUsers = new PanelUsers(this);
    tabbedPane.add("Usuarios", panelUsers);

    panelGroups = new PanelGroup(this, controlador.getClients());
    tabbedPane.add("Grupos", panelGroups);
    tabbedPane.setMinimumSize(new java.awt.Dimension(100, 100));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.gridheight = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.ipadx = 10;
    gridBagConstraints.ipady = 20;
    gridBagConstraints.weightx = 300.0;
    gridBagConstraints.weighty = 300.0;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 1);
    add(tabbedPane, gridBagConstraints);

    createGroup.setText("Crear grupo");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    add(createGroup, gridBagConstraints);
    createGroup.addActionListener(panelGroups);

    addClient.setText("Anadir usuario");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 1);
    add(addClient, gridBagConstraints);
    addClient.addActionListener(panelGroups);

    leaveGroup.setText("Dejar grupo");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 1, 0);
    add(leaveGroup, gridBagConstraints);
    leaveGroup.addActionListener(panelGroups);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClient;
    private javax.swing.JButton createGroup;
    private javax.swing.JButton leaveGroup;
    private javax.swing.JLabel photo;
    private javax.swing.JLabel status;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
    private Gestion controlador;
    private ControladorChat controlChat;
    private PanelUsers panelUsers;
    private PanelGroup panelGroups;
}
